import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenTitle, SectionCard, StatusPill, palette } from "@/components/formpath-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { ANONYMOUS_POSE_LIBRARY_STATUS, ANONYMOUS_POSE_REFERENCES, type AnonymousPoseReference } from "@/lib/anonymous-pose-library";

export default function LibraryScreen() {
  const [selectedId, setSelectedId] = useState(ANONYMOUS_POSE_REFERENCES[0].id);
  const selected = ANONYMOUS_POSE_REFERENCES.find((item) => item.id === selectedId) ?? ANONYMOUS_POSE_REFERENCES[0];
  return <ScreenContainer><FlatList data={ANONYMOUS_POSE_REFERENCES} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><ScreenTitle eyebrow="MOTION LIBRARY" title="16개의 이름 없는 슛폼" detail="각 모델은 선수 이름이나 source 링크 없이 움직임 특성으로만 비교됩니다." /><SectionCard tone="sand"><StatusPill tone="warning">{ANONYMOUS_POSE_LIBRARY_STATUS.profileCount} YOUTUBE POSE CANDIDATES</StatusPill><Text style={styles.notice}>단일 시점 camera-relative pose 자료입니다. 보정된 metric 3D 또는 특정 선수의 복제라고 표시하지 않습니다.</Text></SectionCard><Text style={styles.sectionTitle}>익명 모션 모델</Text></>} renderItem={({ item }) => <PoseRow item={item} selected={item.id === selectedId} onPress={() => { setSelectedId(item.id); haptic.selection(); }} />} ListFooterComponent={<DetailCard reference={selected} />} ItemSeparatorComponent={() => <View style={{ height: 10 }} />} showsVerticalScrollIndicator={false} /></ScreenContainer>;
}
function PoseRow({ item, selected, onPress }: { item: AnonymousPoseReference; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.row, selected && styles.rowSelected, pressed && styles.pressed]}><View style={styles.rowCopy}><Text style={[styles.rowTitle, selected && styles.rowTitleSelected]}>{item.shortLabel}</Text><Text style={[styles.rowDetail, selected && styles.rowDetailSelected]}>{item.styleTitle}</Text></View><View style={[styles.dot, selected && styles.dotSelected]} /></Pressable>; }
function DetailCard({ reference }: { reference: AnonymousPoseReference }) { return <SectionCard tone="navy"><Text style={styles.detailKicker}>움직임 특성</Text><Text style={styles.detailTitle}>{reference.shortLabel}</Text><Text style={styles.detailDescription}>{reference.styleTitle}을 중심으로 한 익명 단일 시점 pose 모델입니다.</Text><View style={styles.metricRow}><Metric label="릴리스" value={reference.traits.releaseElevation} /><Metric label="확장" value={reference.traits.armExtension} /><Metric label="하체" value={reference.traits.lowerBodyDrive} /><Metric label="리듬" value={reference.traits.rhythm} /></View><View style={styles.divider} /><Text style={styles.warningTitle}>사용 경계</Text><Text style={styles.warningText}>카메라 위치·거리·화질에 영향을 받는 상대 pose 추정치입니다. 통증이 있거나 움직임이 불편하면 이 모션을 따르지 마세요.</Text></SectionCard>; }
function Metric({ label, value }: { label: string; value: number }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 32 }, notice: { color: palette.steel, fontSize: 13, lineHeight: 19 }, sectionTitle: { color: palette.ink, fontSize: 18, fontWeight: "800", marginBottom: 12, marginTop: 22 }, row: { alignItems: "center", backgroundColor: palette.white, borderColor: palette.mist, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 12, padding: 15 }, rowSelected: { backgroundColor: "#FFF0E9", borderColor: palette.orange }, rowCopy: { flex: 1, gap: 4 }, rowTitle: { color: palette.ink, fontSize: 16, fontWeight: "800" }, rowTitleSelected: { color: "#B9421E" }, rowDetail: { color: palette.steel, fontSize: 12, lineHeight: 17 }, rowDetailSelected: { color: "#B86A50" }, dot: { backgroundColor: palette.mist, borderRadius: 99, height: 10, width: 10 }, dotSelected: { backgroundColor: palette.orange }, detailKicker: { color: "#FFAB89", fontSize: 12, fontWeight: "800", letterSpacing: 0.9 }, detailTitle: { color: palette.white, fontSize: 26, fontWeight: "800" }, detailDescription: { color: "#C9D8E4", fontSize: 14, lineHeight: 21 }, metricRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 5 }, metric: { alignItems: "center", gap: 2 }, metricValue: { color: palette.white, fontSize: 17, fontWeight: "800" }, metricLabel: { color: "#9FB5C6", fontSize: 11, fontWeight: "700" }, divider: { backgroundColor: "#35526A", height: 1, marginVertical: 3 }, warningTitle: { color: "#FFAB89", fontSize: 13, fontWeight: "800" }, warningText: { color: "#C9D8E4", fontSize: 13, lineHeight: 19 }, pressed: { opacity: 0.8, transform: [{ scale: 0.985 }] } });
